import { useMemo, useState } from "react";
import { Navigate, useLocation, useNavigate } from "react-router-dom";
import { Check, ChevronLeft, ChevronRight, LockOutlined } from "@mui/icons-material";
import { money } from "../../data/products";
import { useStore } from "../../hooks/useStore";
import { orderService } from "../../services/orderService";

const emptyContact = { email: "", firstName: "", lastName: "", phone: "" };
const emptyShipping = { address: "", apartment: "", city: "", country: "Lebanon", postalCode: "" };

export default function CheckoutPage() {
  const navigate = useNavigate();
  const history = { back: () => navigate(-1) };
  const { cart, orders, setOrders, clearCart } = useStore(); const location = useLocation(); const [step,setStep]=useState(1); const [contact,setContact]=useState(emptyContact); const [shipping,setShipping]=useState(emptyShipping); const [order,setOrder]=useState(null); const gift=Boolean(location.state?.gift); const discount=Number(location.state?.discount||0);
  const subtotal=useMemo(()=>cart.reduce((sum,item)=>sum+item.price*item.quantity,0),[cart]); const total=subtotal-discount;
  if(!cart.length&&!order) return <Navigate to="/shop" replace/>;
  const set=(setter,key)=>(event)=>setter((value)=>({...value,[key]:event.target.value}));
  const validContact=contact.email&&contact.firstName&&contact.lastName; const validShipping=shipping.address&&shipping.city&&shipping.country;
  const placeOrder=()=>{const next=orderService.create({cart,contact,shipping,gift,total});setOrders([next,...orders]);setOrder(next);clearCart()};
  if(order) return <main className="orderConfirmation"><span className="orderCheck"><Check/></span><span className="kicker">Order confirmed</span><h1>Thank you, {contact.firstName}.</h1><p>Your Veloura ritual is being prepared with care.</p><div><span>Order number</span><strong>{order.id}</strong><span>Estimated delivery</span><strong>3–5 business days</strong><span>Confirmation</span><strong>{contact.email}</strong></div><a className="button dark" href="/">Return home</a></main>;
  return <main className="checkoutPage"><header><button onClick={()=>history.back()}><ChevronLeft/> Back</button><a className="wordmark" href="/">VELOURA<span>BEAUTY</span></a><span><LockOutlined/> Demo checkout</span></header><div className="checkoutLayout"><section className="checkoutForm"><div className="checkoutSteps">{["Contact","Shipping","Review"].map((label,index)=><span className={step>=index+1?"active":""} key={label}><i>{index+1}</i>{label}</span>)}</div>{step===1&&<CheckoutSection title="Your details" copy="We’ll use these details only for your order updates."><div className="formGrid"><Field label="Email" type="email" value={contact.email} onChange={set(setContact,"email")} wide/><Field label="First name" value={contact.firstName} onChange={set(setContact,"firstName")}/><Field label="Last name" value={contact.lastName} onChange={set(setContact,"lastName")}/><Field label="Phone (optional)" value={contact.phone} onChange={set(setContact,"phone")} wide/></div><button className="button dark checkoutNext" disabled={!validContact} onClick={()=>setStep(2)}>Continue to shipping <ChevronRight/></button></CheckoutSection>}{step===2&&<CheckoutSection title="Where should we send it?" copy="Complimentary standard delivery is included."><div className="formGrid"><Field label="Address" value={shipping.address} onChange={set(setShipping,"address")} wide/><Field label="Apartment (optional)" value={shipping.apartment} onChange={set(setShipping,"apartment")} wide/><Field label="City" value={shipping.city} onChange={set(setShipping,"city")}/><Field label="Postal code" value={shipping.postalCode} onChange={set(setShipping,"postalCode")}/><Field label="Country" value={shipping.country} onChange={set(setShipping,"country")} wide/></div><div className="stepActions"><button onClick={()=>setStep(1)}>Back</button><button className="button dark" disabled={!validShipping} onClick={()=>setStep(3)}>Review order <ChevronRight/></button></div></CheckoutSection>}{step===3&&<CheckoutSection title="Review and place order" copy="Payment is a demo. No card details are collected."><div className="reviewDetails"><div><span>Contact</span><p>{contact.firstName} {contact.lastName}<br/>{contact.email}</p><button onClick={()=>setStep(1)}>Edit</button></div><div><span>Shipping</span><p>{shipping.address}{shipping.apartment&&`, ${shipping.apartment}`}<br/>{shipping.city}, {shipping.country}</p><button onClick={()=>setStep(2)}>Edit</button></div><div><span>Payment</span><p>Demo payment · No charge will be made</p></div></div><button className="button dark full" onClick={placeOrder}>Place demo order · {money(total)}</button></CheckoutSection>}</section><OrderSummary cart={cart} subtotal={subtotal} discount={discount} total={total} gift={gift}/></div></main>;
}
function CheckoutSection({title,copy,children}){return <div className="checkoutSection"><span className="kicker">Step details</span><h1>{title}</h1><p>{copy}</p>{children}</div>}
function Field({label,wide,...props}){return <label className={wide?"wide":""}><span>{label}</span><input required {...props}/></label>}
function OrderSummary({cart,subtotal,discount,total,gift}){return <aside className="checkoutSummary"><h2>Order summary</h2>{cart.map(item=><div className="summaryItem" key={item.id}><span>{item.quantity}×</span><div><strong>{item.name}</strong><small>{item.size}</small></div><b>{money(item.price*item.quantity)}</b></div>)}{gift&&<p className="giftSummary">Signature gift packaging included</p>}<div className="summaryTotals"><p><span>Subtotal</span><b>{money(subtotal)}</b></p>{discount>0&&<p><span>Promotion</span><b>−{money(discount)}</b></p>}<p><span>Delivery</span><b>Complimentary</b></p><p className="total"><span>Total</span><b>{money(total)}</b></p></div></aside>}
