import { Link, useParams } from "react-router-dom";

const policies = {
  shipping: { title: "Shipping & returns", intro: "Clear delivery expectations and a simple, considered return experience.", sections: [["Delivery", "Complimentary standard delivery is offered on orders over $75. Estimated delivery is 3–5 business days after dispatch."], ["Returns", "Unused products in their original packaging may be returned within 30 days of delivery. Final-sale and opened hygiene-sensitive items are not eligible."], ["International orders", "Duties, taxes, and delivery timing are shown at secure checkout when international delivery is available."]] },
  refund: { title: "Refund policy", intro: "Straightforward support when something is not right.", sections: [["Eligibility", "Approved returns are refunded to the original payment method after inspection."], ["Timing", "Please allow 5–10 business days after approval for your financial institution to post the refund."], ["Damaged orders", "Contact our care team within 48 hours of delivery with your order number and clear photographs."]] },
  faq: { title: "Frequently asked questions", intro: "Helpful details about products, orders, and daily rituals.", sections: [["Are Veloura products cruelty-free?", "Yes. Veloura products and ingredients are not tested on animals."], ["How do I choose a routine?", "Use our Routine Builder for a considered starting point based on your skin goals and preferences."], ["Can I change an order?", "Contact customer care as soon as possible. Changes cannot be guaranteed after fulfillment begins."]] },
  track: { title: "Track your order", intro: "Your delivery updates are always close at hand.", sections: [["Tracking link", "When your order dispatches, we send a tracking link to the email used at checkout."], ["No update yet?", "Tracking may take up to 24 hours to refresh after the carrier receives your parcel."], ["Need help?", "Contact customer care with your order number and the email used at checkout."]] },
  privacy: { title: "Privacy", intro: "How Veloura handles the information you choose to share.", sections: [["Information we collect", "We use the details you provide to process orders, deliver support, and improve your shopping experience."], ["How it is used", "We do not sell personal information. Service providers receive only the information required to deliver their part of the service."], ["Your choices", "You may request access, correction, or deletion of your personal information by contacting our care team."]] },
  terms: { title: "Terms", intro: "The terms that apply when browsing and shopping Veloura Beauty.", sections: [["Orders", "Orders are subject to acceptance, availability, and successful payment authorization."], ["Product information", "We work to present product colours and descriptions accurately, though displays and natural batch variation may differ slightly."], ["Product use", "Products should be used as directed. Discontinue use if irritation occurs and seek professional advice when appropriate."]] },
  accessibility: { title: "Accessibility", intro: "A welcoming shopping experience, designed for as many people as possible.", sections: [["Our approach", "We aim for clear structure, keyboard access, readable contrast, meaningful labels, and reduced-motion support."], ["Feedback", "If you encounter a barrier, tell us the page, device, and issue so we can help."], ["Ongoing work", "Accessibility is reviewed as the store evolves and new services are introduced."]] },
};

export default function PolicyPage(){const {policy}=useParams();const content=policies[policy]||policies.shipping;const contact=process.env.REACT_APP_CONTACT_EMAIL||"care@velourabeauty.com";return <main className="policyPage"><span className="kicker">Customer care</span><h1>{content.title}</h1><p className="policyIntro">{content.intro}</p><div>{content.sections.map(([title,copy])=><section key={title}><h2>{title}</h2><p>{copy}</p></section>)}</div><div className="policyActions"><a className="button dark" href={`mailto:${contact}`}>Contact customer care</a><Link className="textLink" to="/shop">Continue shopping</Link></div></main>}
