import { useMemo, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { AnimatePresence, motion } from "framer-motion";
import { Add, CardGiftcard, Close, LocalShippingOutlined, Remove, ShoppingBagOutlined } from "@mui/icons-material";
import { money, PRODUCTS } from "../../data/products";
import { useStore } from "../../hooks/useStore";
import ProductVisual from "../products/ProductVisual";
import { MOTION } from "../../theme/tokens";

export default function CartDrawer({ open, close }) {
  const { cart, updateQuantity, addToCart } = useStore(); const navigate = useNavigate(); const [gift, setGift] = useState(false); const [promo, setPromo] = useState(""); const [applied, setApplied] = useState(false);
  const subtotal = useMemo(() => cart.reduce((sum, item) => sum + item.price * item.quantity, 0), [cart]); const discount = applied ? subtotal * .1 : 0; const recommendation = PRODUCTS.find((p) => !cart.some((item) => item.id === p.id));
  const checkout = () => { close(); navigate("/checkout", { state: { gift, promo: applied ? promo : "", discount } }); };
  return <AnimatePresence>{open && <><motion.button className="drawerOverlay motionOverlay" aria-label="Close bag" onClick={close} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}/><motion.aside className="cartDrawer motionDrawer" initial={{x:"100%"}} animate={{x:0}} exit={{x:"100%"}} transition={MOTION.drawer} aria-label="Shopping bag"><header className="cartHeader"><div><span className="kicker">Your selection</span><h2>Shopping bag</h2></div><button onClick={close} aria-label="Close bag"><Close/></button></header>{cart.length ? <><div className="cartItems">{cart.map((item)=><article className="cartItem" key={item.id}><div className={`cartThumb ${item.color}`}><ProductVisual type={item.type}/></div><div><strong>{item.name}</strong><small>{item.brand} · {item.size}</small><div className="quantity"><button onClick={()=>updateQuantity(item.id,-1)} aria-label={`Remove one ${item.name}`}><Remove/></button><span>{item.quantity}</span><button onClick={()=>updateQuantity(item.id,1)} aria-label={`Add one ${item.name}`}><Add/></button></div></div><b>{money(item.price*item.quantity)}</b></article>)}<label className="giftOption"><input type="checkbox" checked={gift} onChange={(e)=>setGift(e.target.checked)}/><CardGiftcard/><span><strong>Add signature gift packaging</strong><small>Complimentary wrap and handwritten note</small></span></label>{recommendation&&<div className="cartRecommendation"><span className="kicker">Pairs beautifully</span><div><div className={`miniVisual ${recommendation.color}`}><ProductVisual type={recommendation.type}/></div><span><strong>{recommendation.name}</strong><small>{money(recommendation.price)}</small></span><button onClick={()=>addToCart(recommendation)}>Add</button></div></div>}</div><footer className="cartFooter"><form className="promo" onSubmit={(e)=>{e.preventDefault();setApplied(promo.trim().toUpperCase()==="VELOURA10")}}><input value={promo} onChange={(e)=>setPromo(e.target.value)} placeholder="Promo code" aria-label="Promo code"/><button>Apply</button></form>{promo&&<small className={applied?"promoSuccess":"promoHint"}>{applied?"VELOURA10 applied":"Try VELOURA10 for the demo"}</small>}<div><span>Subtotal</span><strong>{money(subtotal-discount)}</strong></div><p><LocalShippingOutlined/> Estimated delivery: 3–5 business days</p><button className="button dark full ripple" onClick={checkout}>Checkout securely</button><button className="textLink" onClick={close}>Continue shopping</button></footer></> : <div className="emptyBag"><ShoppingBagOutlined/><h3>Your bag is waiting.</h3><p>Choose what belongs in your ritual.</p><Link className="button dark" to="/shop" onClick={close}>Shop the collection</Link></div>}</motion.aside></>}</AnimatePresence>;
}
