import { useEffect, useRef, useState } from "react";
import { Link, NavLink, Outlet, useLocation, useNavigate } from "react-router-dom";
import { AnimatePresence, motion } from "framer-motion";
import { AccountCircleOutlined, FavoriteBorder, Menu, Search, ShoppingBagOutlined } from "@mui/icons-material";
import { useStore } from "../hooks/useStore";
import { MOTION } from "../theme/tokens";

export default function Layout({ openCart }) {
  const { cart, wishlist, addSearch } = useStore(); const [menuOpen,setMenuOpen]=useState(false); const [searchOpen,setSearchOpen]=useState(false); const [query,setQuery]=useState(""); const navigate=useNavigate(); const location=useLocation(); const spotlight=useRef(null);
  useEffect(()=>{setMenuOpen(false);window.scrollTo({top:0,behavior:"auto"})},[location.pathname]);
  useEffect(()=>{const fine=window.matchMedia("(hover: hover) and (pointer: fine)").matches;if(!fine)return;const move=(event)=>{if(spotlight.current)spotlight.current.style.transform=`translate3d(${event.clientX-160}px,${event.clientY-160}px,0)`};window.addEventListener("pointermove",move,{passive:true});return()=>window.removeEventListener("pointermove",move)},[]);
  const submit=(event)=>{event.preventDefault();if(query.trim()){addSearch(query);navigate(`/shop?search=${encodeURIComponent(query.trim())}`);setSearchOpen(false);setQuery("")}};
  return <div className="siteShell"><div className="cursorSpotlight" ref={spotlight}/><div className="announcement"><span>Complimentary delivery on orders over $75</span><span className="announcementAlt">Thoughtfully made · Never tested on animals</span></div><header className="siteHeader"><button className="mobileMenu" onClick={()=>setMenuOpen(!menuOpen)} aria-label="Toggle menu"><Menu/></button><Link className="wordmark" to="/">VELOURA<span>BEAUTY</span></Link><nav className={menuOpen?"open":""} aria-label="Main navigation"><NavLink to="/shop">Shop</NavLink><NavLink to="/shop/skincare">Skincare</NavLink><NavLink to="/shop/makeup">Makeup</NavLink><NavLink to="/rituals">Routine builder</NavLink><NavLink to="/shade-match">Shade match</NavLink><NavLink to="/about">Our story</NavLink></nav><div className="headerActions"><button onClick={()=>setSearchOpen(!searchOpen)} aria-label="Search"><Search/></button><Link to="/wishlist" aria-label={`Wishlist with ${wishlist.length} items`}><FavoriteBorder/><span>{wishlist.length}</span></Link><Link to="/profile" aria-label="Beauty profile"><AccountCircleOutlined/></Link><button onClick={openCart} aria-label={`Shopping bag with ${cart.reduce((n,item)=>n+item.quantity,0)} items`}><ShoppingBagOutlined/><span>{cart.reduce((n,item)=>n+item.quantity,0)}</span></button></div></header>{searchOpen&&<form className="searchBar" onSubmit={submit}><Search/><input autoFocus value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search formulas, shades, rituals…" aria-label="Search products"/><button>Search</button></form>}<AnimatePresence mode="wait"><motion.div key={location.pathname+location.search} initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-6}} transition={MOTION.page}><Outlet/></motion.div></AnimatePresence><Footer/></div>;
}
function Footer(){return <footer><div className="footerBrand"><Link className="wordmark" to="/">VELOURA<span>BEAUTY</span></Link><p>Considered beauty for everyday ritual.</p></div><div><h4>Shop</h4><Link to="/shop/skincare">Skincare</Link><Link to="/shop/makeup">Makeup</Link><Link to="/shop/sets">Sets</Link></div><div><h4>Discover</h4><Link to="/rituals">Routine builder</Link><Link to="/shade-match">Shade match</Link><Link to="/profile">Beauty profile</Link></div><div><h4>Care</h4><span>Complimentary delivery over $75</span><span>30-day returns</span><span>care@veloura.example</span></div><div className="footerBottom"><span>© {new Date().getFullYear()} Veloura Beauty</span><span>Privacy · Terms · Accessibility</span></div></footer>}
